; Specification for this document:
; https://tools.ietf.org/html/rfc5234

; # Basic Value types

; ## Numbers

non-zero = "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9";
zero = "0";
digit = zero / non-zero;
number = non-zero *digit ["." 1*digit];

; ## Strings
;
; For simplicity only ASCII characters are defined here,
; but it is highly recommended for all parser / compilers
; to support a more encompassing encoding such as utf-8

squote = %x27 ; single quote
dquote = %x22 ; double quote 
char-not-squote = %x01-26 / %x28-7f; all characters except NULL and single quote
char-not-dquote = %x01-21 / %x23-7f; all characters except NULL and double quote

string = (squote *char-not-squote squote) / (dquote *char-not-dquote dquote);

; ## Boolean

true = %s"true";
false = %s"false";
boolean = true / false;